//
//  FundDetailPresenter.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 16/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundDetailPresentationLogic {
    //  func presentSomething(response: FundDetail.Something.Response)
    func presentFundDetail(response: FundDetail.GetFundDetail.Response)
    func presentError(response: FundDetail.FundDetailError.Response)
}

class FundDetailPresenter: FundDetailPresentationLogic {
    weak var viewController: FundDetailDisplayLogic?
    
    func presentFundDetail(response: FundDetail.GetFundDetail.Response) {
        
        let fund = response.fund
        let viewModel = FundDetail.GetFundDetail.ViewModel(
            title: fund.title ?? "-",
            fundName: fund.fundName ?? "-",
            whatIs: fund.whatIs ?? "-",
            definition: fund.definition ?? "-",
            riskTitle: fund.riskTitle ?? "-",
            risk: fund.risk,
            infoTitle: fund.infoTitle ?? "-",
            moreInfo: fund.moreInfo,
            info: fund.info ?? [],
            downInfo: fund.downInfo ?? [],
            buttonMessage: "Investir",
            buttonTopSpace: 45
        )
        viewController?.displayFundDetail(viewModel: viewModel)
    }
    
    func presentError(response: FundDetail.FundDetailError.Response) {
        var message: String!
        switch response.errorType {
        case .getFundDetail:
            message = response.error.domain
        }
        let viewModel = FundDetail.FundDetailError.ViewModel(message: message, errorType: response.errorType)
        viewController?.displayError(viewModel: viewModel)
    }
}
