//
//  FundDetailPresenter.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 16/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundDetailPresentationLogic
{
//  func presentSomething(response: FundDetail.Something.Response)
}

class FundDetailPresenter: FundDetailPresentationLogic
{
  weak var viewController: FundDetailDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: FundDetail.Something.Response)
//  {
//    let viewModel = FundDetail.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
