//
//  FundDetailInteractor.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 16/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundDetailBusinessLogic
{
//  func doSomething(request: FundDetail.Something.Request)
}

protocol FundDetailDataStore
{
  //var name: String { get set }
}

class FundDetailInteractor: FundDetailBusinessLogic, FundDetailDataStore
{
  var presenter: FundDetailPresentationLogic?
  var worker: FundDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: FundDetail.Something.Request)
//  {
//    worker = FundDetailWorker()
//    worker?.doSomeWork()
//    
//    let response = FundDetail.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
