//
//  InvestmentModels.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Investment
{
  // MARK: Use cases
  
  enum FetchFund
  {
    struct Request
    {
    }
    struct Response
    {
        var fund: Fund
    }
    struct ViewModel
    {
        struct ProfiabilityList {
            var name: String
            var fund: String
            var cdi: String
        }
        var screen: Screen
        var profiabilityList: [ProfiabilityList]
    }
  }
}
