//
//  InvestmentWorker.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class InvestmentWorker
{
    var apiClient: APIClient = APIClient()
    
    func fetchFund(completionHandler: @escaping (Fund?, Error?) -> Void)
    {
        self.apiClient.fetchFund { (fund, error) in
            completionHandler(fund,error)
        }
    }
}
