//
//  InvestmentInteractor.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentBusinessLogic
{
  func doSomething(request: Investment.Something.Request)
}

protocol InvestmentDataStore
{
  //var name: String { get set }
}

class InvestmentInteractor: InvestmentBusinessLogic, InvestmentDataStore
{
  var presenter: InvestmentPresentationLogic?
  var worker: InvestmentWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Investment.Something.Request)
  {
    worker = InvestmentWorker()
    worker?.doSomeWork()
    
    let response = Investment.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
