//
//  InvestmentPresenter.swift
//  Santander
//
//  Created by Orlando Amorim on 15/08/19.
//  Copyright (c) 2019 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentPresentationLogic {
    func presentScreen(response: Result<Investment.Funds.Response, Error>)
}

class InvestmentPresenter: InvestmentPresentationLogic {
    
    weak var viewController: InvestmentDisplayLogic?
  
    // MARK: Present Screen
    func presentScreen(response: Result<Investment.Funds.Response, Error>) {
        switch response {
        case .success(let result):
            let viewModel = Investment.Funds.ViewModel(screen: result.screen)
            viewController?.setupScreen(viewModel: viewModel)
        case .failure(let error):
            viewController?.presentError(error.localizedDescription)
        }
    }
}
