# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movs
  pod 'Reusable'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Moya'
  pod "JMMaskTextField-Swift"

  target 'TesteiOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  #target 'TesteiOSUITests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'iOSSnapshotTestCase'
  #end*/

end
