# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteIOS
  # Alamofire - https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 4.7'
  
  # DLRadioButton - https://github.com/DavydLiu/DLRadioButton
  pod 'DLRadioButton', '~> 1.4'
  
  # JMMaskTextField-Swift - https://github.com/JotaMelo/JMMaskTextField-Swift
  pod 'JMMaskTextField-Swift'

end
