# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteiOS
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Alamofire', '~> 4.5'
  pod 'KeychainSwift', '~> 13.0'
  pod 'MaterialComponents', '~> 70.0.0'

  target 'TesteiOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'Alamofire', '~> 4.5'
  end

  target 'TesteiOSUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'Alamofire', '~> 4.5'
  end

end
