//
//  FormPresenter.swift
//  DesafioSantander
//
//  Created by Fernanda de Lima on 03/09/2018.
//  Copyright (c) 2018 FeLima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormPresentationLogic
{
  func presentFetchedForms(response: Form.FecthForm.Response)
}

class FormPresenter: FormPresentationLogic
{
  weak var viewController: FormDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchedForms(response: Form.FecthForm.Response){
    let viewModel = Form.FecthForm.ViewModel()
    viewController?.displayFetchedForm(viewModel: viewModel)
    
    }
}
