//
//  FormWorker.swift
//  DesafioSantander
//
//  Created by Fernanda de Lima on 03/09/2018.
//  Copyright (c) 2018 FeLima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormWorkerDelegate{
    func formWorker(formWorker: FormWorker, didFetchForm form: FormModal)
}

class FormWorker : FormAPIDelegate{
    var formAPI: FormAPIProtocol = FormAPI()
    var delegate: FormWorkerDelegate?
    
    // MARK: Block implementation
    func fetch(completion: @escaping (FormModal) -> Void)
    {
        formAPI.fetch { (forms) in
            completion(forms)
        }
    }
    
    // MARK: Delegate implementation
    func fetch(){
        formAPI.delegate = self
        formAPI.fetch()
    }
    
    func formAPI(gistAPI: FormAPIProtocol, didFetchForm form: FormModal) {
        delegate?.formWorker(formWorker: self, didFetchForm: form)
    }
  
}
