//
//  FormInteractor.swift
//  DesafioSantander
//
//  Created by Fernanda de Lima on 03/09/2018.
//  Copyright (c) 2018 FeLima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormBusinessLogic
{
  func fetchForm(request: Form.FecthForm.Request)
}

protocol FormDataStore
{
  //var name: String { get set }
}

class FormInteractor: FormBusinessLogic, FormDataStore{
    
    var presenter: FormPresentationLogic?
    var worker: FormWorker?
    var forms: FormModal?
  //var name: String = ""
  
  // MARK: Do something
  
    func fetchForm(request: Form.FecthForm.Request) {
        worker = FormWorker(formStore: FormMemStore())
        
        worker?.fetchForm(completionHandler: { (form) in
            self.forms = form
            let response = Form.FecthForm.Response(formModal: form)
            self.presenter?.presentFetchedForms(response: response)
        })
    }
}
