//
//  ContactFormInteractor.swift
//  iOSTest
//
//  Created by erick.peripolli on 30/07/18.
//  Copyright (c) 2018 Erick Peripolli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactFormBusinessLogic
{
  func doSomething(request: ContactForm.GetContactCells.Request)
}

protocol ContactFormDataStore
{
  //var name: String { get set }
}

class ContactFormInteractor: ContactFormBusinessLogic, ContactFormDataStore
{
  var presenter: ContactFormPresentationLogic?
  var worker: ContactFormWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ContactForm.GetContactCells.Request)
  {
    worker = ContactFormWorker()
    worker?.fetchContactCells(completionHandler: { (contactCells) in
        let response = ContactForm.GetContactCells.Response(contactCells: contactCells)
        self.presenter?.presentSomething(response: response)
    })
  }
}
