//
//  ContactFormPresenter.swift
//  iOSTest
//
//  Created by erick.peripolli on 30/07/18.
//  Copyright (c) 2018 Erick Peripolli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactFormPresentationLogic
{
  func presentSomething(response: ContactForm.GetContactCells.Response)
}

class ContactFormPresenter: ContactFormPresentationLogic
{
  weak var viewController: ContactFormDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ContactForm.GetContactCells.Response)
  {
//    let viewModel = ContactForm.GetContactCells.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
