//
//  ContactFormViewController.swift
//  iOSTest
//
//  Created by erick.peripolli on 30/07/18.
//  Copyright (c) 2018 Erick Peripolli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactFormDisplayLogic: class {
    func displaySomething(viewModel: [ContactForm.GetContactCells.ViewModel])
}
enum Type: Int {
    case field = 1
    case text = 2
    case image = 3
    case checkbox = 4
    case send = 5
}

enum TypeField: Int {
    case text = 1
    case telNumber = 2
    case email = 3
    case null = 100
}

class ContactFormViewController: UIViewController, ContactFormDisplayLogic, UITableViewDataSource {
    
    var interactor: ContactFormBusinessLogic?
    var router: (NSObjectProtocol & ContactFormRoutingLogic & ContactFormDataPassing)?
    
    @IBOutlet weak var tableView: UITableView!
    var cellsViewModels: [ContactForm.GetContactCells.ViewModel]! {
        didSet {
            print("AIAIAIAIAIAIIA")
        }
    }
    

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = ContactFormInteractor()
        let presenter = ContactFormPresenter()
        let router = ContactFormRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        getContactCells()
        self.tableView.dataSource = self
    }
  
    // MARK: Do something
  
    //@IBOutlet weak var nameTextField: UITextField!
  
    func getContactCells() {
        let request = ContactForm.GetContactCells.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: [ContactForm.GetContactCells.ViewModel]) {
        //nameTextField.text = viewModel.name
        DispatchQueue.main.async {
            self.cellsViewModels = viewModel
        }
    }
    
    
    // MARK: TableViewDataSource
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
}
