//
//  ContactsModels.swift
//  santanderTest
//
//  Created by Adauto Oliveira on 26/05/19.
//  Copyright (c) 2019 Adauto Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Contacts
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response{
        var forms: [Form]
    }
    struct ViewModel{
        struct DisplayedForm: Codable {
            var id: Int
            var type: Int
            var message: String
            var typefield: Bool
            var hidden: Bool
            var topSpacing: Double
            var show: Int
            var required: Bool
            
        }
        
        var diplayedForm: [DisplayedForm]
        
  
        
    }
  }
}
