# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteMarcio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'IJProgressView', :git => 'https://github.com/Isuru-Nanayakkara/IJProgressView.git'
  # Pods for TesteMarcio

  target 'TesteMarcioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteMarcioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
