//
//  InvestmentViewController.swift
//  TesteiOS
//
//  Created by Tiago Leme on 28/07/18.
//  Copyright (c) 2018 Tiago Leme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentDisplayLogic: class
{
  func displaySomething(viewModel: Investment.Something.ViewModel)
}

class InvestmentViewController: UITableViewController, InvestmentDisplayLogic
{
  var interactor: InvestmentBusinessLogic?
  var router: (NSObjectProtocol & InvestmentRoutingLogic & InvestmentDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestmentInteractor()
    let presenter = InvestmentPresenter()
    let router = InvestmentRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
    
    //MARK: Outlets
    
    //MARK: Basic Investment Info
    @IBOutlet weak var fundTitle: UILabel!
    @IBOutlet weak var fundName: UILabel!
    @IBOutlet weak var whatIs: UILabel!
    @IBOutlet weak var definition: UILabel!
    @IBOutlet weak var riskTitle: UILabel!
    @IBOutlet weak var riskImage: UIImageView!
    
    //MARK: More Info
    @IBOutlet weak var infoTitle: UILabel!
    
    @IBOutlet weak var month: UILabel!
    @IBOutlet weak var monthFund: UILabel!
    @IBOutlet weak var monthCdi: UILabel!
    @IBOutlet weak var year: UILabel!
    @IBOutlet weak var yearFund: UILabel!
    @IBOutlet weak var yearCdi: UILabel!
    @IBOutlet weak var twelveMonths: UILabel!
    @IBOutlet weak var twelveMonthsFund: UILabel!
    @IBOutlet weak var twelveMonthsCdi: UILabel!
    
    //MARK: Info
    @IBOutlet weak var name1: UILabel!
    @IBOutlet weak var data1: UILabel!
    @IBOutlet weak var name2: UILabel!
    @IBOutlet weak var data2: UILabel!
    @IBOutlet weak var name3: UILabel!
    @IBOutlet weak var data3: UILabel!
    @IBOutlet weak var name4: UILabel!
    @IBOutlet weak var data4: UILabel!
    @IBOutlet weak var name5: UILabel!
    @IBOutlet weak var data5: UILabel!
    @IBOutlet weak var name6: UILabel!
    @IBOutlet weak var data6: UILabel!
    @IBOutlet weak var name7: UILabel!
    @IBOutlet weak var data7: UILabel!
    
    //MARK: Down Info
    @IBOutlet weak var downName1: UILabel!
    @IBOutlet weak var downName2: UILabel!
    @IBOutlet weak var downName3: UILabel!
    @IBOutlet weak var downName4: UILabel!
    @IBOutlet weak var downName5: UILabel!
    
    //MARK: Invest Button
    @IBOutlet weak var invest: UIButton!
    
    
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Investment.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Investment.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
