//
//  InvestmentViewController.swift
//  TesteiOS
//
//  Created by Tiago Leme on 28/07/18.
//  Copyright (c) 2018 Tiago Leme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

protocol InvestmentDisplayLogic: class
{
  func displayFundInfo(viewModel: Investment.FetchFund.ViewModel)
}

class InvestmentViewController: UITableViewController, InvestmentDisplayLogic
{
  var interactor: InvestmentBusinessLogic?
  var router: (NSObjectProtocol & InvestmentRoutingLogic & InvestmentDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestmentInteractor()
    let presenter = InvestmentPresenter()
    let router = InvestmentRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchFundInfo()
  }
    
    //MARK: Outlets
    
    //MARK: Basic Investment Info
    @IBOutlet weak var fundTitle: UILabel!
    @IBOutlet weak var fundName: UILabel!
    @IBOutlet weak var whatIs: UILabel!
    @IBOutlet weak var definition: UILabel!
    @IBOutlet weak var riskTitle: UILabel!
    @IBOutlet weak var riskImage: UIImageView!
    
    //MARK: More Info
    @IBOutlet weak var infoTitle: UILabel!
    
    @IBOutlet weak var month: UILabel!
    @IBOutlet weak var monthFund: UILabel!
    @IBOutlet weak var monthCdi: UILabel!
    @IBOutlet weak var year: UILabel!
    @IBOutlet weak var yearFund: UILabel!
    @IBOutlet weak var yearCdi: UILabel!
    @IBOutlet weak var twelveMonths: UILabel!
    @IBOutlet weak var twelveMonthsFund: UILabel!
    @IBOutlet weak var twelveMonthsCdi: UILabel!
    
    //MARK: Info
    @IBOutlet weak var name1: UILabel!
    @IBOutlet weak var data1: UILabel!
    @IBOutlet weak var name2: UILabel!
    @IBOutlet weak var data2: UILabel!
    @IBOutlet weak var name3: UILabel!
    @IBOutlet weak var data3: UILabel!
    @IBOutlet weak var name4: UILabel!
    @IBOutlet weak var data4: UILabel!
    @IBOutlet weak var name5: UILabel!
    @IBOutlet weak var data5: UILabel!
    @IBOutlet weak var name6: UILabel!
    @IBOutlet weak var data6: UILabel!
    @IBOutlet weak var name7: UILabel!
    @IBOutlet weak var data7: UILabel!
    
    //MARK: Down Info
    @IBOutlet weak var downName1: UILabel!
    @IBOutlet weak var downName2: UILabel!
    @IBOutlet weak var downName3: UILabel!
    @IBOutlet weak var downName4: UILabel!
    @IBOutlet weak var downName5: UILabel!
    
    //MARK: Invest Button
    @IBOutlet weak var invest: UIButton!
    
    
    //MARK: - Actions
    
    @IBAction func baixarPressed(_ sender: UIButton) {
        guard let url = URL(string: "https://www.google.com") else {
            return
        }
        let safariViewController = SFSafariViewController(url: url, entersReaderIfAvailable: true)
        self.present(safariViewController, animated: true)
    }
  
    //MARK: Fetch Investment Fund Information

    func fetchFundInfo() {
        let request = Investment.FetchFund.Request()
        interactor?.fetchFundInfo(request: request)
    }
    
    //MARK: - Display Info received from Presenter
    func displayFundInfo(viewModel: Investment.FetchFund.ViewModel) {
    //MARK: - Basic Investment Info
    self.fundTitle.text = viewModel.displayedInvestmentFund.fundTitle
    self.fundName.text = viewModel.displayedInvestmentFund.fundName
    self.whatIs.text = viewModel.displayedInvestmentFund.whatIs
    self.definition.text = viewModel.displayedInvestmentFund.definition
    self.riskTitle.text = viewModel.displayedInvestmentFund.riskTitle
    self.riskImage.image = viewModel.displayedInvestmentFund.riskImage
    
    //MARK: - More Info
    self.infoTitle.text = viewModel.displayedInvestmentFund.infoTitle
    self.year.text = viewModel.displayedInvestmentFund.year
    self.yearCdi.text = viewModel.displayedInvestmentFund.yearCdi
    self.yearFund.text = viewModel.displayedInvestmentFund.yearFund
    self.month.text = viewModel.displayedInvestmentFund.month
    self.monthCdi.text = viewModel.displayedInvestmentFund.monthCdi
    self.monthFund.text = viewModel.displayedInvestmentFund.monthFund
    self.twelveMonths.text = viewModel.displayedInvestmentFund.twelveMonths
    self.twelveMonthsCdi.text = viewModel.displayedInvestmentFund.twelveMonthsCdi
    self.twelveMonthsFund.text = viewModel.displayedInvestmentFund.twelveMonthsFund
    
    //MARK: - Info
    self.name1.text = viewModel.displayedInvestmentFund.info[0].0
    self.data1.text = viewModel.displayedInvestmentFund.info[0].1
    self.name2.text = viewModel.displayedInvestmentFund.info[1].0
    self.data2.text = viewModel.displayedInvestmentFund.info[1].1
    self.name3.text = viewModel.displayedInvestmentFund.info[2].0
    self.data3.text = viewModel.displayedInvestmentFund.info[2].1
    self.name4.text = viewModel.displayedInvestmentFund.info[3].0
    self.data4.text = viewModel.displayedInvestmentFund.info[3].1
    self.name5.text = viewModel.displayedInvestmentFund.info[4].0
    self.data5.text = viewModel.displayedInvestmentFund.info[4].1
    self.name6.text = viewModel.displayedInvestmentFund.info[5].0
    self.data6.text = viewModel.displayedInvestmentFund.info[5].1
    self.name7.text = viewModel.displayedInvestmentFund.info[6].0
    self.data7.text = viewModel.displayedInvestmentFund.info[6].1
    
    //MARK: - Down Info
    self.downName1.text = viewModel.displayedInvestmentFund.downInfo[0].0
    self.downName2.text = viewModel.displayedInvestmentFund.downInfo[1].0
    self.downName3.text = viewModel.displayedInvestmentFund.downInfo[2].0
    self.downName4.text = viewModel.displayedInvestmentFund.downInfo[3].0
    self.downName5.text = viewModel.displayedInvestmentFund.downInfo[4].0
    
    
  }
}
