//
//  FormPresenter.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 21/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormPresentationLogic{
  func presentCells(response:FormModels.FetchCell.Response)
}

class FormPresenter: FormPresentationLogic{
  weak var viewController: FormDisplayLogic?
  
  // MARK: Do something
  
  func presentCells(response: FormModels.FetchCell.Response){
    viewController?.displayCells(viewModel: FormModels.FetchCell.ViewModel(displayedCells: response.cells))
    
  }
}
