//
//  FormWorker.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FormWorker{
    var api = API()
    
    func fetchCells(completionHandler: @escaping ([Cell]) -> Void){
        api.fetchCells{cells in
            DispatchQueue.main.async {
                completionHandler(cells)
            }
        }
    }
}
