//
//  FormInteractor.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 21/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormBusinessLogic{
    func fetchCells(request: FormModels.FetchCell.Request)
}

protocol FormDataStore{
    var cells: [Cell]? { get }
}

class FormInteractor:FormBusinessLogic, FormDataStore{
    var presenter: FormPresentationLogic?
    var worker: FormWorker?
    var cells: [Cell]?
    
    // MARK: Fetch Cells
    
    func fetchCells(request: FormModels.FetchCell.Request){
        worker = FormWorker()
        worker?.fetchCells { (cells) -> Void in
            self.cells = cells
            let response = FormModels.FetchCell.Response(cells: cells)
            self.presenter?.presentCells(response: response)
        }
    }
}
