//
//  FormRouter.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FormRoutingLogic{
    func routeToMessage(segue: UIStoryboardSegue?)
    func routeToInvestimentos(segue: UIStoryboardSegue?)
}

protocol FormDataPassing{
    var dataStore: FormDataStore? { get }
}

class FormRouter: NSObject, FormRoutingLogic, FormDataPassing{
    weak var viewController: FormViewController?
    var dataStore: FormDataStore?
    
    //MARK: Routing
    
    func routeToMessage(segue: UIStoryboardSegue?){
        if let segue = segue {
            let destinationVC = segue.destination as! MessageViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMessage(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "MessageViewController") as! MessageViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMessage(source: dataStore!, destination: &destinationDS)
            navigateToMessage(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToInvestimentos(segue: UIStoryboardSegue?){
        if let segue = segue {
            let destinationVC = segue.destination as! InvestimentosViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToInvestimentos(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "InvestimentosViewController") as! InvestimentosViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToInvestimentos(source: dataStore!, destination: &destinationDS)
            navigateToInvestimentos(source: viewController!, destination: destinationVC)
        }
    }
    
    //MARK: Navigation
    func navigateToMessage(source: FormViewController, destination: MessageViewController){
        source.show(destination, sender: nil)
    }
    
    func navigateToInvestimentos(source: FormViewController, destination: InvestimentosViewController){
        source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    func passDataToMessage(source: FormDataStore, destination: inout MessageDataStore){
        destination.name = source.name
    }
    
    func passDataToInvestimentos(source: FormDataStore, destination: inout InvestimentosDataStore){
        destination.name = source.name
    }
}
