//
//  FormModels.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//  see http://clean-swift.com
//

import UIKit

enum FormModels{
    
    // MARK: Use cases
    enum FetchCell{
        struct Request{}
        struct Response{
            var cells: [Cell]
        }
        
        struct ViewModel{
            struct DisplayedCell {
                var id: Int
                var type: Int
                var message: String
                var typefield: Int
                var hidden: Bool
                var topSpacing: Float
                var show: Int
                var required: Bool
            }
            
            var displayedCells: [Cell]
        }
    }
}
