language: objective-c
osx_image: xcode9.4

podfile: Investimentos/Podfile

script:
  - xcodebuild -workspace Investimentos/Investimentos.xcworkspace -scheme 'Investimentos' -sdk iphonesimulator build
  - xcodebuild test -workspace Investimentos/Investimentos.xcworkspace -scheme 'InvestimentosTests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'
  - xcodebuild test -workspace Investimentos/Investimentos.xcworkspace -scheme 'InvestimentosUITests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'