# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SantanderTeste' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 4.7'
 pod 'PhoneNumberKit', '~> 2.1'
  # Pods for SantanderTeste
 pod 'SkyFloatingLabelTextField', '~> 3.0'

  target 'SantanderTesteTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'SantanderTesteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
