//
//  ContactWorker.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ContactWorker {
  
  private let networkManager: NetworkManager
  
  init(networkManager: NetworkManager = NetworkManager()) {
    self.networkManager = networkManager
  }
  
  func fetchForm(request: Contact.Form.Request, completion: @escaping (Result<FormData>) -> ()) {
    networkManager.fetchForm(request: request) { result in
      completion(result)
    }
  }
}
