//
//  ContactInteractor.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactBusinessLogic
{
  func doSomething(request: Contact.Something.Request)
}

protocol ContactDataStore
{
  //var name: String { get set }
}

class ContactInteractor: ContactBusinessLogic, ContactDataStore
{
  var presenter: ContactPresentationLogic?
  var worker: ContactWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Contact.Something.Request)
  {
    worker = ContactWorker()
    worker?.doSomeWork()
    
    let response = Contact.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
