//
//  ContactModels.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Contact {
  // MARK: Use cases
  enum Send {
    struct Request{
      let values: [Value]
    }
    struct Response {}
    struct ViewModel {}
  }
  
  enum Form {
    struct Request{}
    
    struct Response {
      let cells: [Cell]
      let error: Error?
      
      init(cells: [Cell] = [], error: Error? = .none) {
        self.cells = cells
        self.error = error
      }
    }
    struct ViewModel {
      let cells: [Cell]
      let error: Error?
      
      init(cells: [Cell] = [], error: Error? = .none) {
        self.cells = cells
        self.error = error
      }
    }
  }
  
}
