//
//  ContactPresenter.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactPresentationLogic {
  func presentForm(response: Contact.Form.Response)
  func presentSuccesseMessage(response: Contact.Send.Response)
  func presentErrorMessage(response: Contact.Form.Response)
}

class ContactPresenter: ContactPresentationLogic {
  weak var viewController: ContactDisplayLogic?
  
  // MARK: Present Form
  func presentForm(response: Contact.Form.Response) {
    let viewModel = Contact.Form.ViewModel(cells: response.cells)
    viewController?.displayForm(viewModel: viewModel)
  }
  
  // MARK: Present Success Message
  func presentSuccesseMessage(response: Contact.Send.Response) {
    let viewModel = Contact.Send.ViewModel()
    viewController?.displaySuccessMessage(viewModel: viewModel)
  }
  
  // MARK: Present Error Message
  func presentErrorMessage(response: Contact.Form.Response) {
    let viewModel = Contact.Form.ViewModel(error: response.error)
    viewController?.displayErrorMessage(viewModel: viewModel)
  }
}
