//
//  ContactInteractor.swift
//  TesteiOS
//
//  Created by Gustavo Melki Leal on 22/04/2018.
//  Copyright (c) 2018 GustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol ContactBusinessLogic
{
  func doSomething(request: Contact.Request)
}

protocol ContactDataStore
{
  //var name: String { get set }
}

class ContactInteractor: ContactBusinessLogic, ContactDataStore
{
  var presenter: ContactPresentationLogic?
  var worker: ContactWorker?
  
  let disposeBag = DisposeBag()
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Contact.Request)
  {
    worker = ContactWorker()
    worker?.doSomeWork()
    
    CellManager.getCells().subscribe(onNext: { (cells) in
      let response = Contact.Response(cells: cells)
      self.presenter?.presentSomething(response: response)
    }, onError: { (error) in
      print(error)
    }, onCompleted: {
      print("Completed")
    }).disposed(by: disposeBag)
    
   
  }
}
