# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'

  target 'InvestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
