# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'

  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'TPKeyboardAvoiding', '~> 1.3.1'
  pod 'RxSwift', '~> 4.1.2'
  pod 'RxCocoa', '~> 4.1.2'
  pod 'BEMCheckBox', '~> 1.4.1'

  target 'InvestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
