//
//  InvestmentPresenter.swift
//  FinForm
//
//  Created by Gustavo on 25/07/18.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentPresentationLogic
{
  func presentSomething(response: Investment.Something.Response)
}

class InvestmentPresenter: InvestmentPresentationLogic
{
  weak var viewController: InvestmentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Investment.Something.Response)
  {
    let viewModel = Investment.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
