//
//  InvestmentViewController.swift
//  FinForm
//
//  Created by Gustavo on 25/07/18.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentDisplayLogic: class
{
  func displayFetchedScreen(viewModel: Investment.FetchScreen.ViewModel)
}

class InvestmentViewController: UIViewController, InvestmentDisplayLogic
{
  var interactor: InvestmentBusinessLogic?
  var router: (NSObjectProtocol & InvestmentRoutingLogic & InvestmentDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestmentInteractor()
    let presenter = InvestmentPresenter()
    let router = InvestmentRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    moreInfoTableViewHeightConstraint.constant = 500
    infoTableViewHeightConstraint.constant = 500
    doFetchScreen()
  }
  
    @IBAction func test(_ sender: Any) {
        riskView.setRist(risk: 5)
    }
  
    // MARK: Properties
    @IBOutlet weak var moreInfoTableViewHeightConstraint: NSLayoutConstraint!
    @IBOutlet weak var infoTableViewHeightConstraint: NSLayoutConstraint!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var fundNameLabel: UILabel!
    @IBOutlet weak var riskView: RiskView!
    @IBOutlet weak var definitionLabel: UILabel!
    @IBOutlet weak var riskTitleLabel: UILabel!
    @IBOutlet weak var infoTitleLabel: UILabel!
    @IBOutlet weak var moreInfoTableView: UITableView!
    @IBOutlet weak var infoTableView: UITableView!
    @IBOutlet weak var whatIsLabel: UILabel!
    @IBOutlet weak var button: UIButton!
    
    
// MARK: Fetch Screen
  func doFetchScreen()
  {
    let request = Investment.FetchScreen.Request()
    interactor?.fetchScreen(request: request)
  }
  
  func displayFetchedScreen(viewModel: Investment.FetchScreen.ViewModel)
  {
    
  }
    
    // MARK: Private Methods
    
    private func bindScreen(screen:Screen)
    {
        
    }
}
