//
//  InvestmentModels.swift
//  FinForm
//
//  Created by Gustavo on 25/07/18.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Investment
{
  // MARK: Use cases
  
  enum FetchScreen
  {
    struct Request
    {
    }
    struct Response
    {
        var screen:Screen?
        var noInternet:Bool = false
    }
    struct ViewModel
    {
        var screen:Screen?
        
        var monthTitle:String = ""
        var yearTitle:String = ""
        var twelveMonthsTitle:String = ""
        
        var fundTitle:String = ""
        var cdiTitle:String = ""
        
        var alertTitle:String?
        var alertMessage:String?
    }
  }
}
