//
//  InvestmentPresenter.swift
//  FinForm
//
//  Created by Gustavo on 25/07/18.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentPresentationLogic
{
  func presentFetchedScreen(response: Investment.FetchScreen.Response)
}

class InvestmentPresenter: InvestmentPresentationLogic
{
  weak var viewController: InvestmentDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedScreen(response: Investment.FetchScreen.Response)
  {
    var viewModel = Investment.FetchScreen.ViewModel()
    
    if response.noInternet{
        let title = String.loc("NO_INTERNET_ACCESS_ALERT_TITLE")
        let message = String.loc("NO_INTERNET_ACCESS_ALERT_MESSAGE")
        
        viewModel.alertTitle = title
        viewModel.alertMessage = message
        
        viewController?.displayFetchedScreen(viewModel: viewModel)
    } else{
        
        viewModel.fundTitle = "Fundo"
        viewModel.cdiTitle = "CDI"
        
        viewModel.monthTitle = "No mês"
        viewModel.yearTitle = "No ano"
        viewModel.twelveMonthsTitle = "12 meses"
        
        viewModel.screen = response.screen
        viewController?.displayFetchedScreen(viewModel: viewModel)
        
    }
    
  }
}
