# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Floating Mountain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MaterialComponents/TextFields'
  pod 'SwiftValidators'
  
  # Pods for Floating Mountain

  target 'Floating MountainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Floating MountainUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
