//
//  FormWorker.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 22/05/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FormWorker
{
  func fetchCells(completionHandler: @escaping ([Cell]) -> Void)
  {
    var request = URLRequest(url: URL(string: "https://floating-mountain-50292.herokuapp.com/cells.json")!)
    request.httpMethod = "GET"
    
    URLSession.shared.dataTask(with: request, completionHandler: { data, response, error -> Void in
        do {
            let jsonDecoder = JSONDecoder()
            let responseModel = try jsonDecoder.decode(CellArray.self, from: data!)
            
            var cells = [Cell]()
            cells = responseModel.cells!
            
            DispatchQueue.main.async {
                completionHandler(cells)
            }
        } catch {
            print("JSON Serialization error")
            print(error)
        }
    }).resume()
  }
}
