//
//  FormPresenter.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 22/05/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormPresentationLogic
{
  func presentFetchedCells(response: Form.FetchCells.Response)
}

class FormPresenter: FormPresentationLogic
{
  weak var viewController: FormDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedCells(response: Form.FetchCells.Response)
  {
    let viewModel = Form.FetchCells.ViewModel(cells: response.cells)
    viewController?.displayCells(viewModel: viewModel)
  }
}
