platform :ios, '9.0'

target 'IOSApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSApp
	
	pod 'TextFieldFloatingPlaceholder'

  target 'IOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
