# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteIOS
  pod 'AnyFormatKit'
  
  target 'TesteIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
