# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SantanderInvestmentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SantanderInvestmentApp
  pod 'SnapKit', '~> 4.0.0'

  target 'SantanderInvestmentAppTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble', '~> 7.0.2'
	pod 'Nimble-Snapshots'
	pod 'Quick'
  end

end
