//
//  FundsModels.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Funds
{
  // MARK: Use cases
  
  struct Request
  {
  }
  struct Response
  {
  }
  struct ViewModel
  {
  }
}
