//
//  FundsModels.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Funds {
  // MARK: Use cases
  enum Download {
    struct Request {
      let url: String?
    }
    struct Response {}
    struct ViewModel {}
  }
  
  enum Get {
    struct Request {}
    struct Response {
      let fund: Fund?
      let error: Error?
      
      init(fund: Fund? = .none, error: Error? = .none) {
        self.fund = fund
        self.error = error
      }
    }
    struct ViewModel {
      let fund: Fund?
      let error: Error?
      
      init(fund: Fund? = .none, error: Error? = .none) {
        self.fund = fund
        self.error = error
      }
    }
  }
}
