//
//  FundsRouter.swift
//  TesteiOS
//
//  Created by Brendoon Ryos on 21/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

@objc protocol FundsRoutingLogic {
  func routeToDownloadData()
}

protocol FundsDataPassing {
  var dataStore: FundsDataStore? { get }
}

class FundsRouter: NSObject, FundsRoutingLogic, FundsDataPassing {
  weak var viewController: FundsViewController?
  var dataStore: FundsDataStore?
  
  // MARK: Routing
  func routeToDownloadData() {
    guard let string = dataStore?.url, let url = URL(string: string) else { return }
    let safariViewController = SFSafariViewController(url: url)
    navigateToDownloadData(source: viewController!, destination: safariViewController)
  }

  // MARK: Navigation
  func navigateToDownloadData(source: FundsViewController, destination: SFSafariViewController) {
    source.present(destination, animated: true)
  }
  
  // MARK: Passing data
//  func passDataToSomewhere(source: FundsDataStore, destination: inout SomewhereDataStore) {
//    destination.name = source.name
//  }
}
