//
//  FormModels.swift
//  TesteiOS
//
//  Created by Gustavo Melki on 20/04/2018.
//  Copyright (c) 2018 GustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Form {
  // MARK: Use cases
    struct Request {
      let screen: Screen?

      
    }
    struct Response {
      let screen: Screen?

      
    }
    struct ViewModel {
      let screen: Screen?
  
      
  }
}
