//
//  FormWorker.swift
//  TesteiOS
//
//  Created by Gustavo Melki on 20/04/2018.
//  Copyright (c) 2018 GustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FormWorker
{
  func doSomeWork()
  {
  }
}
