//
//  FormViewController.swift
//  TesteiOS
//
//  Created by Gustavo Melki on 20/04/2018.
//  Copyright (c) 2018 GustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya
import RxSwift

protocol FormDisplayLogic: class
{
  func displaySomething(viewModel: Form.ViewModel)
}

class FormViewController: UIViewController, FormDisplayLogic
{
  var interactor: FormBusinessLogic?
  var router: (NSObjectProtocol & FormRoutingLogic & FormDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FormInteractor()
    let presenter = FormPresenter()
    let router = FormRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Form.Request(screen: nil)
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Form.ViewModel)
  {
    print(viewModel.screen)
    
    FundManager.getFund().subscribe(onNext: { (fund) in
      print(fund)
    }, onError: { (error) in
      print(error)
    }, onCompleted: {
      print("Completed")
    }).disposed(by: DisposeBag())
  }
  
}
