//
//  FormPresenter.swift
//  TesteiOS
//
//  Created by Gustavo Melki on 20/04/2018.
//  Copyright (c) 2018 GustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormPresentationLogic
{
  func presentSomething(response: Form.Response)
}

class FormPresenter: FormPresentationLogic
{
  weak var viewController: FormDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Form.Response)
  {
    let viewModel = Form.ViewModel(screen: response.screen)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
