//
//  FundRouter.swift
//  SantanderInvestmentApp
//
//  Created by Michel de Sousa Carvalho on 23/05/18.
//  Copyright (c) 2018 Michel de Sousa Carvalho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

protocol FundRoutingLogic: class {
    func routerToSafari()
}


class FundRouter: FundRoutingLogic {
    var viewController: FundViewController?
    
    func routerToSafari() {
        if let url = URL(string: "https://www.google.com") {
            let config = SFSafariViewController.Configuration()
            config.entersReaderIfAvailable = true
            
            let vc = SFSafariViewController(url: url, configuration: config)
            self.viewController?.present(vc, animated: true)
        }
    }
}
