//
//  FundInteractor.swift
//  SantanderInvestmentApp
//
//  Created by Michel de Sousa Carvalho on 23/05/18.
//  Copyright (c) 2018 Michel de Sousa Carvalho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class FundInteractor {
    var worker: FundWorker
    var presenter: FundPresenter?
    
    init(worker: FundWorker = FundWorker(), presenter: FundPresenter = FundPresenter()) {
        self.worker = worker
        self.presenter = presenter
    }
    
    func fetchFund() {
        worker.getFund(completion: { fund in
            self.presenter?.presentFund(fund: fund)
        }, failure: { error in
            self.presenter?.presentError(error: error)
        })
    }
}
