//
//  FundWorker.swift
//  SantanderInvestmentApp
//
//  Created by Michel de Sousa Carvalho on 23/05/18.
//  Copyright (c) 2018 Michel de Sousa Carvalho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FundWorker {

    func getFund(session: URLSessionProtocol = URLSession.shared,
                 completion: @escaping(_ fund: FundModel)->(),
                 failure: @escaping(_ error: NetworkErrorResponse) ->()) {
        
        guard let url = URL(string: Constants.Request.fund) else {
            fatalError("Must provide a URL")
        }
        
        let resource = Resource<ScreenModel>.init(url: url, parseJSON: { result in
            return result
        })
        

        
        Request.load(session: session, resource: resource, completion: { result in
            switch result {
            case let .success(screen):
                completion(screen.screen)
            case let .failureNetwork(error):
                failure(error)
            }
            
        })
        
    }
    

}


