//
//  FundInteractor.swift
//  DesafioSantander
//
//  Created by Fernanda de Lima on 03/09/2018.
//  Copyright (c) 2018 FeLima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundBusinessLogic
{
  func doSomething(request: Fund.Something.Request)
}

protocol FundDataStore
{
  //var name: String { get set }
}

class FundInteractor: FundBusinessLogic, FundDataStore
{
  var presenter: FundPresentationLogic?
  var worker: FundWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Fund.Something.Request)
  {
    worker = FundWorker()
    worker?.doSomeWork()
    
    let response = Fund.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
