//
//  ContactPresenter.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactPresentationLogic
{
  func presentForm(response: Contact.fetchFormCells.Response)
}

class ContactPresenter: ContactPresentationLogic
{
  weak var viewController: ContactDisplayLogic?
  
  // MARK: Do something
  
  func presentForm(response: Contact.fetchFormCells.Response)
  {
    let viewModel = Contact.fetchFormCells.ViewModel(displayCells: prepareViewModel(response.cells))
    viewController?.displayForm(viewModel: viewModel)
  }
    
    func prepareViewModel(_ cells: [Cells]) -> [Contact.fetchFormCells.ViewModel.DisplayCells] {
        
        let list = cells.map {
            Contact.fetchFormCells.ViewModel.DisplayCells(hidden: $0.hidden ?? true, id: $0.id ?? 0, topSpacing: $0.topSpacing ?? 0, typefield: $0.typefield ?? 0, required: $0.required ?? false, message: $0.message ?? "", type: $0.type ?? 0, show: $0.show ?? 0)
        }
        
        return list
    }
}
