//
//  ContactPresenter.swift
//  Santander
//
//  Created by Orlando Amorim on 11/08/19.
//  Copyright (c) 2019 Santander. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactPresentationLogic {
    func presentForm(response: Contact.Form.Response)
    func presentSuccess()
}

class ContactPresenter: ContactPresentationLogic {
    
    weak var viewController: ContactDisplayLogic?
  
    // MARK: Present Form
    func presentForm(response: Contact.Form.Response) {
        viewController?.setupForm(response: response)
    }
    
    // MARK: Present Success
    func presentSuccess() {
        viewController?.presentSuccess()
    }
}
