//
//  ContactPresenter.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactPresentationLogic
{
  func presentSomething(response: Contact.Something.Response)
}

class ContactPresenter: ContactPresentationLogic
{
  weak var viewController: ContactDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Contact.Something.Response)
  {
    let viewModel = Contact.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
