//
//  ContactRouter.swift
//  Santander
//
//  Created by Orlando Amorim on 11/08/19.
//  Copyright (c) 2019 Santander. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ContactRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ContactDataPassing {
  var dataStore: ContactDataStore? { get }
}

class ContactRouter: NSObject, ContactRoutingLogic, ContactDataPassing {
  weak var viewController: ContactViewController?
  var dataStore: ContactDataStore?
  
  // MARK: Routing
  
  // MARK: Navigation
//  
//  func navigateToSomewhere(source: ContactViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
//  }
//  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ContactDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
