//
//  ContactViewController.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactDisplayLogic: class
{
  func displayForm(viewModel: Contact.fetchFormCells.ViewModel)
}

class ContactViewController: BaseViewController, ContactDisplayLogic
{
  var interactor: ContactBusinessLogic?
  var router: (NSObjectProtocol & ContactRoutingLogic & ContactDataPassing)?
    var scrollView: UIScrollView = UIScrollView()
    var scrollContainerView: UIView = UIView()
    var sendButton: RoundedButton = RoundedButton(frame: CGRect.zero)
    var fieldList: [CustomTextField] = []
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ContactInteractor()
    let presenter = ContactPresenter()
    let router = ContactRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchFormCells()
  }
  
  // MARK: Do something
  
    func configUI(viewModel: Contact.fetchFormCells.ViewModel) {
        
        self.view.addSubview(self.scrollView)
        self.scrollView.snp.makeConstraints({ (make) in
            make.left.right.top.bottom.equalTo(0)
        })
        
        self.scrollView.bounces = false
        self.scrollView.addSubview(self.scrollContainerView)
        
        self.scrollContainerView.snp.makeConstraints { (make) in
            make.left.right.top.bottom.equalTo(0)
            make.width.equalTo(self.view)
            make.height.equalTo(self.view)
        }
        
        let screenTitleLabel = UILabel()
        screenTitleLabel.font = UIFont.DINPro_Medium(ofSize: 16)
        screenTitleLabel.textColor = Color.black
        screenTitleLabel.text = "Contato"
        
        self.scrollContainerView.addSubview(screenTitleLabel)
        screenTitleLabel.snp.makeConstraints { (make) in
            make.centerX.equalTo(self.scrollContainerView)
            make.height.equalTo(22)
            make.top.equalTo(self.scrollContainerView).offset(24)
        }
        
        var lastItemReference: UIView = screenTitleLabel
        
        for item in viewModel.displayCells {
//            item.topSpacing = 35
            let topSpacing = 20
            
            let type = FieldType.init(rawValue: item.type)!
            
            if type == .text {
                let field = UILabel()
                field.font = UIFont.DINPro_Medium(ofSize: 16)
                field.textColor = Color.gray
                field.text = item.message
                field.adjustsFontSizeToFitWidth = true
                field.minimumScaleFactor = 0.5
                
                self.scrollContainerView.addSubview(field)
                field.snp.makeConstraints { (make) in
                    make.top.equalTo(lastItemReference.snp.bottom).offset(topSpacing)
                    make.height.equalTo(20)
                    make.left.equalTo(25)
                    make.right.equalTo(-25)
                }
                
                lastItemReference = field
            }
            
            if type == .field {
                
                var field = CustomTextField(frame: CGRect.zero)
                let textFieldType = TextFieldType(rawValue: item.typefield)!
                
                if textFieldType == .email {
                    field = EmailTextField(frame: CGRect.zero)
                }
                
                //fix api error
                if textFieldType == .telNumber || item.id == 6 {
                    field = PhoneTextField(frame: CGRect.zero)
                }

                field.setLabelText(text: item.message)
                
                self.scrollContainerView.addSubview(field)
                field.snp.makeConstraints { (make) in
                    make.top.equalTo(lastItemReference.snp.bottom).offset(topSpacing)
                    make.height.equalTo(56)
                    make.left.equalTo(25)
                    make.right.equalTo(-25)
                }
            
                lastItemReference = field
                field.delegate = self
                self.fieldList.append(field)
            }
            
            if type == .checkbox {
                
                let field = CustomCheckBox(frame: CGRect.zero)
                field.setText(text: item.message)
                
                self.scrollContainerView.addSubview(field)
                field.snp.makeConstraints { (make) in
                    make.top.equalTo(lastItemReference.snp.bottom).offset(47)
                    make.height.equalTo(20)
                    make.left.equalTo(25)
                    make.right.equalTo(-25)
                }
                
                lastItemReference = field
            }
            
            if type == .send {
                
                let field = RoundedButton(frame: CGRect.zero)
                field.setTitle(item.message, for: .normal)
                
                self.scrollContainerView.addSubview(field)
                field.snp.makeConstraints { (make) in
                    make.top.equalTo(lastItemReference.snp.bottom).offset(38)
                    make.height.equalTo(50)
                    make.left.equalTo(25)
                    make.right.equalTo(-25)
                }
                
                lastItemReference = field
                self.sendButton = field
            }
        }
        
        self.sendButton.enableButton(enable: false)
        self.sendButton.addTarget(self, action: #selector(sendClick), for: .touchUpInside)
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard))
        self.scrollContainerView.addGestureRecognizer(tap)
    }
  //@IBOutlet weak var nameTextField: UITextField!
  
  func fetchFormCells()
  {
    self.showLoader()
    let request = Contact.fetchFormCells.Request()
    interactor?.fetchFormCells(request: request)
  }
  
  func displayForm(viewModel: Contact.fetchFormCells.ViewModel)
  {
    self.hideLoader()
    self.configUI(viewModel: viewModel)
    //nameTextField.text = viewModel.name
  }
    
    @objc func sendClick() {
        self.router?.showSuccessView(source: self)
    }
    
    @objc func dismissKeyboard() {
        //Causes the view (or one of its embedded text fields) to resign the first responder status.
        view.endEditing(true)
    }
}

extension ContactViewController: CustomTextFieldDelegate {
    
    func returnTaped() {
        self.view.endEditing(true)
    }
    
    func validationChanged() {
        
        for field in self.fieldList {
            if !field.fieldIsValid {
                self.sendButton.enableButton(enable: false)
                return
            }
        }
        
        self.sendButton.enableButton(enable: true)
    }
}
