//
//  ContactModels.swift
//  Santander
//
//  Created by Orlando Amorim on 11/08/19.
//  Copyright (c) 2019 Santander. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Contact {
    // MARK: Use cases
    enum Form {
        struct Request {
            var sendFormData: ContactFormDataRequest
        }
        struct Response {
            var result: Result<ContactForm, Error>
        }
        struct ViewModel {
    
        }
    }
}
