//
//  ContactWorker.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ContactWorker
{
    var apiClient: APIClient = APIClient()
    
    func fetchFormCells(completionHandler: @escaping (FormCells?, Error?) -> Void)
    {
        self.apiClient.fetchFormCells { (formCells, error) in
            completionHandler(formCells, error)
        }
    }
}
