//
//  ContactInteractor.swift
//  Santander
//
//  Created by Gabriel vieira on 4/22/18.
//  Copyright (c) 2018 Gabriel vieira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactBusinessLogic
{
    func fetchFormCells(request: Contact.fetchFormCells.Request)
}

protocol ContactDataStore
{
  //var name: String { get set }
}

class ContactInteractor: ContactBusinessLogic, ContactDataStore
{
  var presenter: ContactPresentationLogic?
  var worker: ContactWorker = ContactWorker()
  //var name: String = ""
  
  // MARK: Do something
  
    func fetchFormCells(request: Contact.fetchFormCells.Request)
    {
        self.worker.fetchFormCells { (formCells, error) in

            guard let _formCells = formCells?.cells else {
                //handle error
                //presenter show error
                return
            }
            let response = Contact.fetchFormCells.Response(cells: _formCells)
            self.presenter?.presentForm(response: response)
        }
    }
}
