//
//  FundViewController.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundDisplayLogic: class{
    func displayFunds(viewModel: FundModel.Screen.ViewModel)
}

class FundViewController: UIViewController, FundDisplayLogic{
    var interactor: FundBusinessLogic?
    var router: (NSObjectProtocol & FundRoutingLogic & FundDataPassing)?
    var displayedFunds: [Fund] = []
    @IBOutlet weak var bottoMenuStack: BottomMenuStack?
    @IBOutlet weak var navigationBar: UINavigationBar?
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?){
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup(){
        let viewController = self
        let interactor = FundInteractor()
        let presenter = FundPresenter()
        let router = FundRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?){
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad(){
        super.viewDidLoad()
        fechFunds()
    }
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fechFunds(){
        let request = FundModel.Screen.Request()
        interactor?.fechFunds(request: request)
    }
    
    func displayFunds(viewModel: FundModel.Screen.ViewModel){
        displayedFunds = viewModel.funds
        tableView.reloadData()
    }
    
    //MARK:- IBActions
    @IBAction func contatoButtonClicked(_ sender: Any) {
        router?.routeBack()
    }
    
    @IBAction func btnShareClicked() {
        let bounds = UIScreen.main.bounds
        UIGraphicsBeginImageContextWithOptions(bounds.size, true, 0.0)
        self.view.drawHierarchy(in: bounds, afterScreenUpdates: false)
        let img = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        let objectsToShare = [img as Any]
        let activityVC = UIActivityViewController(activityItems: objectsToShare, applicationActivities: nil)
        activityVC.excludedActivityTypes = [UIActivityType.airDrop, UIActivityType.addToReadingList]
        self.present(activityVC, animated: true, completion: nil)
    }
    
}

extension FundViewController: UITableViewDataSource, UITableViewDelegate{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    //MARK:- Table view config
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell{
        
        
        var cell = tableView.dequeueReusableCell(withIdentifier: "cell")
        if cell == nil {
            cell = UITableViewCell(style: .value1, reuseIdentifier: "cell")
        }
        
        cell!.textLabel?.text = "TESTE1\(indexPath.item)"
        return cell!
        
        
    }
}
