//
//  FundInteractor.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundBusinessLogic{
    func fechFunds(request: FundModel.Screen.Request)
}

protocol FundDataStore{
    //var name: String { get set }
}

class FundInteractor: FundBusinessLogic, FundDataStore{
    var presenter: FundPresentationLogic?
    var worker: FundWorker?
    
    func fechFunds(request: FundModel.Screen.Request){
        worker = FundWorker()
        worker?.fetchFunds(onCompletion: { (invests) in
            let response = FundModel.Screen.Response(funds: invests)
            self.presenter?.presentFunds(response: response)
        })
    }
}
