//
//  InvestmentInteractor.swift
//  SantanderExample
//
//  Created by Luan Henrique Damasceno Costa on 09/05/2018.
//  Copyright (c) 2018 Luan Henrique Damasceno Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentBusinessLogic {
  func fetchInvestment()
}

protocol InvestmentDataStore {}

class InvestmentInteractor: InvestmentBusinessLogic, InvestmentDataStore {
  
  var presenter: InvestmentPresentationLogic?
  var worker: InvestmentWorker?
  
  func fetchInvestment() {
    worker?.getInvestment(onSuccess: { [weak self] (screen: InvestmentFundResponse) in
      let response = Investment.GetInvestment.Response(fundResponse: screen)
      self?.presenter?.presentFetchedInvestment(response: response)
    }, onFailure: { [weak self] (error) in
      let response = Investment.GetInvestment.ErrorResponse(error: error)
      self?.presenter?.presentFetchedError(response: response)
    })
  }
}
