//
//  InvestmentWorker.swift
//  SantanderExample
//
//  Created by Luan Henrique Damasceno Costa on 10/05/2018.
//  Copyright (c) 2018 Luan Henrique Damasceno Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya
import Result

class InvestmentWorker {
  
  // To mock the server use stubClosure: MoyaProvider.immediatelyStub -> This use the mock jsons setted on the project, using the Sample Data from Moya Target Type
  var provider: MoyaProvider<InvestmentTargetType> = MoyaProvider<InvestmentTargetType>(/*stubClosure: MoyaProvider.immediatelyStub*/)
  
  func getInvestment(onSuccess: @escaping (InvestmentFundResponse) -> Void, onFailure: @escaping (ServiceError) -> Void) {
    
    let target = InvestmentTargetType.getInvestment()
    
    provider.requestCodableObject(
      target,
      onSuccess: { (screen: InvestmentFundResponse) in
        onSuccess(screen)
    }, onFailure: { (error) in
      onFailure(error)
    })
  }
  
  // For test purpose
  func setProvider(provider: MoyaProvider<InvestmentTargetType>) {
    self.provider = provider
  }
}
