# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Investimentos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Investimentos
  pod "EVReflection/Alamofire"

  target 'InvestimentosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestimentosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
