//
//  MessageRouter.swift
//  LuizProcessoTesteSantader
//
//  Created by Luiz Otavio Processo on 28/09/19.
//  Copyright (c) 2019 Luiz Otavio Processo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MessageRoutingLogic{
    func routeToForm()
    func routeToInvest()
}

protocol MessageDataPassing{
    var dataStore: MessageDataStore? { get }
}

class MessageRouter: NSObject, MessageRoutingLogic, MessageDataPassing{
    weak var viewController: MessageViewController?
    var dataStore: MessageDataStore?
  
  // MARK: Routing

    func routeToForm() {
        let destination = FormViewController()
        navigateToForm(source: viewController!, destination: destination)
    }
    
    func routeToInvest() {
        let destination = InvestViewController()
        navigateToInvest(source: viewController!, destination: destination)
    }
    

  // MARK: Navigation
  
    func navigateToForm(source: MessageViewController, destination: FormViewController){
        source.navigationController?.pushViewController(destination, animated: false)
    }
    func navigateToInvest(source: MessageViewController, destination: InvestViewController){
        source.navigationController?.pushViewController(destination, animated: false)
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MessageDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
