//
//  MessageModels.swift
//  LuizProcessoTesteSantader
//
//  Created by Luiz Otavio Processo on 28/09/19.
//  Copyright (c) 2019 Luiz Otavio Processo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Message{
  // MARK: Use cases
  
  enum Something{
    struct Request{
    }
    struct Response{
    }
    struct ViewModel{
    }
  }
}
