//
//  investmentoInteractor.swift
//  santanderTest
//
//  Created by Adauto Oliveira on 27/05/19.
//  Copyright (c) 2019 Adauto Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol investmentoBusinessLogic
{
  func doSomething(request: investmento.Something.Request)
}

protocol investmentoDataStore
{
  //var name: String { get set }
}

class investmentoInteractor: investmentoBusinessLogic, investmentoDataStore
{
  var presenter: investmentoPresentationLogic?
  var worker: investmentoWorker?
  //var name: String = ""
    
    var screens: [Screen]?
  
  // MARK: Do something
  
  func doSomething(request: investmento.Something.Request)
  {
    worker = investmentoWorker()
    worker?.doSomeWork()
    
    guard let screens = screens else {return}
    
    let response = investmento.Something.Response(screen: screens)
    presenter?.presentSomething(response: response)
  }
}
