//
//  ContactWorkerTests.swift
//  Floating Mountain
//
//  Created by Leonardo Oliveira on 9/16/18.
//  Copyright (c) 2018 Leonardo Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Floating_Mountain
import XCTest

class ContactWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ContactWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupContactWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupContactWorker() {
        sut = ContactWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        let expectation = XCTestExpectation(description: "fetch form")
        let request = Contact.FetchForm.Request()
        // When
        sut.fetchForm(request: request) { (_, _) in
            expectation.fulfill()
        }
        // Then
        wait(for: [expectation], timeout: 2.0)
    }
}
