# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvestmentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InvestmentApp
  pod 'SnapKit', '~> 4.0.0'
  target 'InvestmentAppTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble', '~> 7.0.2'
	pod 'Nimble-Snapshots'
	pod 'Quick'
  end

  target 'InvestmentAppUITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble', '~> 7.0.2'
	pod 'Quick'
  end

end
