//
//  HomeInteractor.swift
//  SantanderExample
//
//  Created by Luan Henrique Damasceno Costa on 08/05/2018.
//  Copyright (c) 2018 Luan Henrique Damasceno Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
  func showInvestmentController()
  func showContactController()
}

protocol HomeDataStore {
  var investementController: InvestmentViewController { get set }
  var contactController: ContactViewController { get set }
  var selectedIndex: Int { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {

  var presenter: HomePresentationLogic?
  var selectedIndex: Int = 0
  
  var investementController: InvestmentViewController = UIStoryboard.init(name: "Investment", bundle: nil).instantiateViewController(withIdentifier: "InvestmentViewController") as! InvestmentViewController
  
  var contactController: ContactViewController = UIStoryboard.init(name: "Contact", bundle: nil).instantiateViewController(withIdentifier: "ContactViewController") as! ContactViewController
  
  func showInvestmentController() {
    presenter?.presentInvestmentController()
  }
  
  func showContactController() {
    presenter?.presentContactController()
  }
}
