//
//  HomePresenter.swift
//  SantanderExample
//
//  Created by Luan Henrique Damasceno Costa on 08/05/2018.
//  Copyright (c) 2018 Luan Henrique Damasceno Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic: class {
  func presentInvestmentController()
  func presentContactController()
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
  
  func presentInvestmentController() {
    viewController?.displayInvestmentController()
  }
  
  func presentContactController() {
    viewController?.displayContactController()
  }
  
}
