//
//  ShowInvestmentInteractor.swift
//  iOSTest
//
//  Created by erick.peripolli on 29/07/18.
//  Copyright (c) 2018 Erick Peripolli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowInvestmentBusinessLogic {
  func getInvestmentInfo(request: ShowInvestment.GetInvestmentInfo.Request)
}

protocol ShowInvestmentDataStore {
    var investment: Investment? { get set }
}

class ShowInvestmentInteractor: ShowInvestmentBusinessLogic, ShowInvestmentDataStore {
    var presenter: ShowInvestmentPresentationLogic?
    var worker: ShowInvestmentWorker?
    var investment: Investment?
  
    // MARK: Do something
  
    func getInvestmentInfo(request: ShowInvestment.GetInvestmentInfo.Request) {
        worker = ShowInvestmentWorker()
        worker?.fetchInvestmentInfo(completionHandler: { (investment) in
            self.investment = investment
            let response = ShowInvestment.GetInvestmentInfo.Response(investment: investment)
            self.presenter?.presentInvestmentInfo(response: response)
        })
        
    }
}
