//
//  FormWorker.swift
//  LuizProcessoTesteSantader
//
//  Created by Luiz Otavio Processo on 26/09/19.
//  Copyright (c) 2019 Luiz Otavio Processo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FormWorker{
    func requestFromAPI(completionHandler: @escaping (FormViewInfo) -> Void ){
        let url = URL(string: "https://floating-mountain-50292.herokuapp.com/cells.json")
        let task = URLSession.shared.dataTask(with: url!){(data,response, error) in
            DispatchQueue.main.async{
                if let data = data{
                    let decoder = JSONDecoder()
                    do{
                        let decodedData = try decoder.decode(FormViewInfo.self, from: data)
                        completionHandler(decodedData)
                    }catch{
                        print(error.localizedDescription)
                        let objArray:[ViewInfoObj] = []
                        let emptyInfo = FormViewInfo(cells: objArray)
                        completionHandler(emptyInfo)
                    }
                }
            }
        }
        task.resume()
    }
}

