//
//  FundosViewController.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 28/06/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundosDisplayLogic: class
{
  func displayFundScreen(viewModel: Fundos.Something.ViewModel)
}

class FundosViewController: UIViewController, FundosDisplayLogic
{
  var interactor: FundosBusinessLogic?
  var router: (NSObjectProtocol & FundosRoutingLogic & FundosDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FundosInteractor()
    let presenter = FundosPresenter()
    let router = FundosRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Fundos.Something.Request()
    interactor?.fetchFund(request: request)
  }
  
  func displayFundScreen(viewModel: Fundos.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
    print(viewModel)
  }
}
