//
//  FundosPresenter.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 28/06/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundosPresentationLogic
{
  func presentFetchedFund(response: Fundos.Something.Response)
}

class FundosPresenter: FundosPresentationLogic
{
  weak var viewController: FundosDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedFund(response: Fundos.Something.Response)
  {
    let viewModel = Fundos.Something.ViewModel(fund: response.fund)
    viewController?.displayFundScreen(viewModel: viewModel)
  }
}
