//
//  FundosModels.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 28/06/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Fundos
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var fund: Fund
    }
    struct ViewModel
    {
        struct FundScreen {
            var title: String
            var fundName: String
            var whatIs: String
            var definition: String
            var riskTitle: String
            var infoTitle: String
            var moreInfoMonthFund: String
            var moreInfoMonthCDI: String
            var moreInfoYearFund: String
            var moreInfoYearCDI: String
            var moreInfo12monthsFund: String
            var moreInfo12monthsCDI: String
        }
        
        var fundScreen: FundScreen
        var riskCollectionModels: [RiskCellCollectionViewCell.ViewModel]
    }
  }
}
