//
//  FundosWorker.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 28/06/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FundosWorker
{
    func fetchFund(completionHandler: @escaping (Fund) -> Void)
    {
        var request = URLRequest(url: URL(string: "https://floating-mountain-50292.herokuapp.com/fund.json")!)
        request.httpMethod = "GET"
        
        URLSession.shared.dataTask(with: request, completionHandler: { data, response, error -> Void in
            do {
                let jsonDecoder = JSONDecoder()
                let responseModel = try jsonDecoder.decode(Fund.self, from: data!)
                
                DispatchQueue.main.async {
                    completionHandler(responseModel)
                }
            } catch {
                print("JSON Serialization error")
                print(error)
            }
        }).resume()
    }
}
