//
//  ContactSuccessPresenter.swift
//  Floating Mountain
//
//  Created by Leonardo Oliveira on 9/16/18.
//  Copyright (c) 2018 Leonardo Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ContactSuccessPresentationLogic {
    func presentSomething(response: ContactSuccess.Something.Response)
}

class ContactSuccessPresenter: ContactSuccessPresentationLogic {
    weak var viewController: ContactSuccessDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ContactSuccess.Something.Response) {
        let viewModel = ContactSuccess.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
