//
//  ContactSuccessInteractor.swift
//  Floating Mountain
//
//  Created by Leonardo Oliveira on 9/16/18.
//  Copyright (c) 2018 Leonardo Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ContactSuccessBusinessLogic {
    func doSomething(request: ContactSuccess.Something.Request)
}

protocol ContactSuccessDataStore {
    //var name: String { get set }
}

class ContactSuccessInteractor: ContactSuccessBusinessLogic, ContactSuccessDataStore {
    var presenter: ContactSuccessPresentationLogic?
    var worker: ContactSuccessWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ContactSuccess.Something.Request) {
        worker = ContactSuccessWorker()
        worker?.doSomeWork()
        
        let response = ContactSuccess.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
