# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Teste Santander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AnimatedTextInput'
  pod 'JMMaskTextField-Swift'
  pod 'DLRadioButton', '~> 1.4'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  
  # Pods for Teste Santander

  target 'Teste SantanderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AnimatedTextInput'
    pod 'JMMaskTextField-Swift'
    pod 'DLRadioButton', '~> 1.4'
    pod 'Alamofire'
    pod 'SwiftyJSON', '~> 4.0'
  end

#  target 'Teste SantanderUITests' do
#    inherit! :search_paths
    # Pods for testing
#    pod 'AnimatedTextInput'
#    pod 'JMMaskTextField-Swift'
#    pod 'DLRadioButton', '~> 1.4'
#    pod 'Alamofire'
#    pod 'SwiftyJSON', '~> 4.0'
#  end

end
