# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Teste Santander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Teste Santander
  pod 'Alamofire', '~> 4.9.1'
  pod 'SwiftMaskTextfield', '~> 1.1'
  
  target 'Teste SantanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
