//
//  FormModels.swift
//  FinForm
//
//  Created by Gustavo Luís Soré on 23/07/2018.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Form
{
  // MARK: Use cases
  
  enum FetchCells
  {
    struct Request
    {
    }
    struct Response
    {
        var cells:[Cell]
        var noInternt:Bool = false
    }
    struct ViewModel
    {
        var cellsMetaData:[CellMetaData]
        var noInternet:Bool = false
    }
  }
}
