//
//  FormInteractor.swift
//  FinForm
//
//  Created by Gustavo Luís Soré on 23/07/2018.
//  Copyright (c) 2018 Sore. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormBusinessLogic
{
  func fetchCells(request: Form.FetchCells.Request)
  func showHideCell(request: Form.ShowHideCell.Request)
}

protocol FormDataStore
{
    var arrayMetaData: [CellMetaData] { get set }
}

class FormInteractor: FormBusinessLogic, FormDataStore
{

  var presenter: FormPresentationLogic?
  var worker: CellWorker?
    
    // MARK: Data Store
  var arrayMetaData: [CellMetaData] = []
  
  // MARK: Fetch Cells
    func fetchCells(request: Form.FetchCells.Request) {
        worker = CellWorker(cellEngine: CellRequester())
        worker?.fetchCells(completionHandler: { (result) in
            switch result{
            case .Success(let cells):
                let response = Form.FetchCells.Response.init(arrayMetaData: self.generateMetaDataArray(cells: cells), noInternt: false)
                self.arrayMetaData = self.generateMetaDataArray(cells: cells)
                self.presenter?.presentFetchedCells(response: response)
            case .Failure(let error):
                switch error{
                case .RequestError(let requestRrror):
                    switch requestRrror{
                    case .NoInternetAcces:
                        let response = Form.FetchCells.Response.init(arrayMetaData: [], noInternt: true)
                        self.presenter?.presentFetchedCells(response: response)
                    default:
                        let response = Form.FetchCells.Response.init(arrayMetaData: [], noInternt: true)
                        self.presenter?.presentFetchedCells(response: response)
                        break
                    }
                    break
                default:
                    let response = Form.FetchCells.Response.init(arrayMetaData: [], noInternt: false)
                    self.presenter?.presentFetchedCells(response: response)
                    break
                }
            }
        })
    }
    
  // MARK: Show / Hide Cell
    func showHideCell(request: Form.ShowHideCell.Request) {
        let cellMetaData = request.cellMetaData
        
        let result = FormWorker().didSelect(cellMetaData: cellMetaData, arrayMetaData: self.arrayMetaData)
        self.arrayMetaData[result.index] = result.cellMetaData
        
        let response = Form.ShowHideCell.Response.init(cellMetaData: result.cellMetaData, index: result.index, show: result.show)
        presenter?.showHideCell(response: response)
    }
    
    // MARK: Private utils methods
    private func generateMetaDataArray(cells:[Cell]) -> [CellMetaData]{
        var arrayCellsMetaData:[CellMetaData] = []
        for cell in cells{
            var cellMetaData = CellMetaData()
            cellMetaData.cell = cell
            arrayCellsMetaData.append(cellMetaData)
        }
        return arrayCellsMetaData
    }
}
