//
//  FormRouter.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 14/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FormRoutingLogic {
    func routeToSuccess(segue: UIStoryboardSegue?)
}

protocol FormDataPassing {
    var dataStore: FormDataStore? { get }
}

class FormRouter: NSObject, FormRoutingLogic, FormDataPassing {
    weak var viewController: FormViewController?
    var dataStore: FormDataStore?
    
    func routeToSuccess(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: "Success", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "Success") as! SuccessViewController
        navigateToSuccess(source: viewController!, destination: destinationVC)
    }
    
    func navigateToSuccess(source: FormViewController, destination: SuccessViewController) {
        source.show(destination, sender: nil)
    }
}
