//
//  FormWorker.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 14/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FormWorker {
    
    func getFormCells(completion: @escaping ([FormCell]?, Error?) -> Void) {
        let apiManager = FundsServiceApiManager.shared
        apiManager.getFormCells { (formCells, error) in
            guard let formCells = formCells else {
                completion(nil, error)
                return
            }
            
            completion(formCells, nil)
        }
    }
    
    func validateField(text: String, typeField: TypeField) -> Bool {
        switch typeField {
        case .email:
            return FieldValidation.isValid(email: text)
        case .telNumber:
            return FieldValidation.isValid(phoneNumber: text)
        case .text:
            return FieldValidation.isValid(text: text)
        }
    }
}
