//
//  FormInteractor.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 14/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormBusinessLogic {
    func doSomething(request: Form.Something.Request)
}

protocol FormDataStore {
    //var name: String { get set }
}

class FormInteractor: FormBusinessLogic, FormDataStore {
    var presenter: FormPresentationLogic?
    var worker: FormWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Form.Something.Request) {
        worker = FormWorker()
        worker?.doSomeWork()
        
        let response = Form.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
