//
//  FormPresenter.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 14/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormPresentationLogic {
    func presentSomething(response: Form.Something.Response)
}

class FormPresenter: FormPresentationLogic {
    weak var viewController: FormDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Form.Something.Response) {
        let viewModel = Form.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
