//
//  ContactWorker.swift
//  Floating Mountain
//
//  Created by Leonardo Oliveira on 9/14/18.
//  Copyright (c) 2018 Leonardo Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class ContactWorker {
    
    func fetchForm(request: Contact.FetchForm.Request, completion: @escaping (Form?, Error?) -> Void) {
        let service = Service.floatingMountain
        service.request(resource: .cells, completion: completion)
    }
    
    func sendForm(request: Contact.SendForm.Request, completion: @escaping () -> Void) {
        completion()
    }
    
}
