# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Santander-Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Santander-Test

	pod 'Moya'
  pod 'StatusAlert'
  pod 'IQKeyboardManagerSwift'

  target 'Santander-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Santander-TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
