//
//  InvestimentosPresenter.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentosPresentationLogic
{
  func presentSomething(response: Investimentos.Something.Response)
}

class InvestimentosPresenter: InvestimentosPresentationLogic
{
  weak var viewController: InvestimentosDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Investimentos.Something.Response)
  {
    let viewModel = Investimentos.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
