//
//  InvestimentosModels.swift
//  Camila-TesteiOS
//
//  Created by camila oliveira on 20/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum InvestimentoModels{
  // MARK: Use cases
  
  enum Investimento{
    struct Request{}
    struct Response{}
    struct ViewModel{
        typealias data = (found: Float, CDI: Float)
        struct MoreInfo {
            var time: String
            var data: data
        }
        
        struct Info {
            var name: String
            var data: String
        }
        
        struct DownInfo {
            var name: String
            var data: URL?
        }
        
        struct StartInfo {
            var title: String
            var foundName: String
            var whatIs: String
            var definition: String
            var risckTitle: String
            var rick: Int
            var infoTitle: String
        }
        
        struct Investimento {
            var start: StartInfo
            var more: MoreInfo
            var info: Info
            var down: DownInfo
        }
        
        var fechedFounds: [Investimento]
    }
  }
}
