//
//  FormViewControllerTests.swift
//  TesteiOS
//
//  Created by lucas.eiji.saito on 22/05/18.
//  Copyright (c) 2018 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteiOS
import XCTest

class FormViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: FormViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupFormViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupFormViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "FormViewController") as! FormViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class FormViewControllerOutputSpy: FormViewControllerOutput
  {
    // MARK: Method call expectations
    var fetchCellsCalled = false
    
    // MARK: Spied methods
    func fetchCells(request: Form.FetchCells.Request)
    {
        fetchCellsCalled = true
    }
  }
  
  // MARK: Tests
    
    func testShouldFetchCellsWhenViewIsLoaded()
    {
        // Given
        let formViewControllerOutputSpy = FormViewControllerOutputSpy()
        sut.interactor = formViewControllerOutputSpy
        
        // When
        loadView()
        
        // Then
        XCTAssert(formViewControllerOutputSpy.fetchCellsCalled, "Should fetch cells when the view is loaded")
    }
  
  func testDisplayCells()
  {
    // Given
    let viewModel = Form.FetchCells.ViewModel()
    
    // When
    loadView()
    sut.displayCells(viewModel: viewModel)
    
    // Then
    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
  }
}
