//
//  SuccessViewController.swift
//  Santander-Test
//
//  Created by Matheus Ribeiro on 16/05/19.
//  Copyright (c) 2019 Matheus Ribeiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SuccessViewController: UIViewController {
    
    @IBOutlet weak var thankYouLabel: UILabel!
    @IBOutlet weak var sendNewMessageButton: UIButton!
    
    var router: (NSObjectProtocol & SuccessRoutingLogic)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        let viewController = self
        let router = SuccessRouter()
        viewController.router = router
        router.viewController = viewController
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureLayout()
    }
    
    private func configureLayout() {
        thankYouLabel.textColor = UIColor.getColorDarkGray
        sendNewMessageButton.tintColor = UIColor.getColorDarkRed
    }
    
    @IBAction func sendNewMessageButton(_ sender: Any) {
        router?.routeToForm(segue: nil)
    }
}
