//
//  ContactInteractor.swift
//  SantanderExample
//
//  Created by Luan Henrique Damasceno Costa on 13/05/2018.
//  Copyright (c) 2018 Luan Henrique Damasceno Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactBusinessLogic {
  func fetchContactForm()
}

protocol ContactDataStore {}

class ContactInteractor: ContactBusinessLogic, ContactDataStore {
  var presenter: ContactPresentationLogic?
  var worker: ContactWorker?
  
  func fetchContactForm() {
    worker?.getContactForms(onSuccess: { [weak self] (contactForm: ContactFormResponse) in
      let response = Contact.Form.Response(form: contactForm)
      self?.presenter?.presentFetchedContact(form: response)
    }, onFailure: { [weak self] (error) in
      let response = Contact.Form.ErrorResponse(error: error)
      self?.presenter?.presentFetchedError(error: response)
    })
  }
}
